%YAML:1.0
cam_id: 1
image_width: 640
image_height: 480
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 552.48966, 0., 346.17560, 0.,
       553.85769, 232.07749, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -0.02206,   0.06584,   -0.00124,   0.00577,  0.00000 ]