%YAML:1.0

#### Settings for `r4-007` dataset, revise for specific dataset accordingly. #####

# Accepted feature depth bounds
upper_depth: 10000.0
lower_depth: 300.0

# for feature detection
scale_facotr: 1.2
max_level: 5
max_feature_num: 2000
feature_sigma: 0.5


# How many loops in optimizer iteration
local_iter: 11
global_iter: 12

# 1 for print debug info, 0 for not
local_print: 0
global_print: 0

# 1 for verbose, 0 for non-verbose
local_verbose: 0
global_verbose: 0


# Robust kernel for 2d MapPoint constraint
th_huber2: 5.991 


# For odometry uncertanty
odo_x_uncertain: 0.01
odo_y_uncertain: 0.01
odo_theta_uncertain: 0.01

# For odometry noise (in a moment) (unit: mm, rad)
odo_x_steady_noise: 1
odo_y_steady_noise: 1
odo_theta_steady_noise: 0.005

# For plane motion constraint
plane_motion_xrot_info: 1e6
plane_motion_yrot_info: 1e6
plane_motion_z_info: 1

# Tracking frequency
fps: 20

# How many images
img_num: 1501
#3106

# Add plane motion constraint
add_plane_motion: 1


# For map storage
## 1 if use previously saved map, 0 if not
use_prev_map: 0
## 1 if save map when exit, o if not
save_new_map: 1
## 1 if disable SLAM and do localization only (use_prev_map must be 1), 0 if do SLAM
localization_only: 0
## map file config
read_map_file_name: "odoslam.map"
read_map_file_path: "/home/xiaoyu/Downloads/dataset/save_map/"
write_map_file_name: "odoslam.map"
write_map_file_path: "/home/xiaoyu/Downloads/dataset/save_map/"
write_traj_file_name: "se2clam_odo.txt"
write_traj_file_path: "/home/xiaoyu/Downloads/dataset/save_map/"


mappub_scale_ratio: 300
gm_vcl_num_min_match_mp: 12
gm_vcl_num_min_match_kp: 24
gm_vcl_ratio_min_match_kp: 0.05
gm_dcl_min_kfid_offset: 20 
gm_dcl_min_score_best: 0.05
